import arrow from './arrow-down 4.png'
import bell from './bell.png'
import logo from './escodesign-logo.png'
import moon from './moon.png'
import search from './search.png'
import share from './share.png'
import sun from './sun.png'
import thumb from './thumbsup.png'
import watermark from './watermark.png'
import filler1 from './filler1.png'
import filler2 from './filler2.png'
import filler3 from './filler3.png'
import filler4 from './filler4.png'
import filler5 from './filler5.png'
import ofcday from './ofcday.png'
import ofcnight from './ofcnight.png'
import service from './service.png'
import reviews from './reviews.png'
import cart from './cart.png'
import lists from './lists.png'
import products from './products.png'
import modal from './modal.png'
import faqs from './faqs.png'

export {arrow, bell, logo, moon, search, share, sun, thumb, watermark, filler1, filler2, filler3, filler4, filler5,ofcday,ofcnight, service, reviews, cart, lists, products, modal, faqs}